SELECT to_char(SALES_DATE,'yyyy-mm-dd') as sales_date, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM(SELECT
    USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
FROM
    ONLINE_SALE
UNION ALL
SELECT
    NULL as USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
FROM
    OFFLINE_SALE)
where to_char(SALES_DATE, 'MM') = 03
order by SALES_DATE asc, PRODUCT_ID asc, USER_ID asc;