SELECT A.ANIMAL_ID, A.NAME
FROM (SELECT O.ANIMAL_ID AS ANIMAL_ID, O.NAME AS NAME, I.DATETIME, O.DATETIME, O.DATETIME-I.DATETIME
FROM ANIMAL_OUTS O JOIN ANIMAL_INS I 
ON O.ANIMAL_ID = I.ANIMAL_ID
ORDER BY O.DATETIME-I.DATETIME DESC) A
WHERE ROWNUM <3;