SELECT
	TO_CHAR(OS.SALES_DATE, 'YYYY') AS YEAR,
    EXTRACT(MONTH FROM OS.SALES_DATE) AS MONTH,    
    UI.GENDER AS GENDER,
    COUNT(DISTINCT OS.USER_ID) AS USERS
FROM
	ONLINE_SALE OS
JOIN
	USER_INFO UI
ON OS.USER_ID = UI.USER_ID
HAVING UI.GENDER IS NOT NULL
GROUP BY 
	TO_CHAR(OS.SALES_DATE, 'YYYY'),
    EXTRACT(MONTH FROM OS.SALES_DATE),
    UI.GENDER
ORDER BY YEAR, MONTH, GENDER