-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * O.TOTAL AS TOTAL_SALES
FROM
    FOOD_PRODUCT P
JOIN 
(SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL
FROM
    FOOD_ORDER
WHERE TO_CHAR(PRODUCE_DATE, 'YYYYMM') = 202205
GROUP BY PRODUCT_ID) O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY P.PRICE * O.TOTAL DESC, P.PRODUCT_ID ASC