-- 코드를 입력하세요
SELECT LTRIM(TO_CHAR(DATETIME, 'HH24'), '0') AS HOUR, COUNT(*) FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'HH24')
HAVING TO_CHAR(DATETIME, 'HH24') BETWEEN 9 AND 19
ORDER BY TO_CHAR(DATETIME, 'HH24')
