SELECT M.MEMBER_NAME,
    R.REVIEW_TEXT,
    TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM
    REST_REVIEW R
JOIN
    MEMBER_PROFILE M
ON
    R.MEMBER_ID = M.MEMBER_ID

WHERE R.MEMBER_ID =
(SELECT 
    MEMBER_ID    
FROM
(SELECT 
    MEMBER_ID, COUNT(REVIEW_ID) AS COUNT
FROM
    REST_REVIEW
GROUP BY
    MEMBER_ID
ORDER BY COUNT(REVIEW_ID) DESC)
WHERE ROWNUM=1)
ORDER BY
    TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') ASC, REVIEW_TEXT ASC