-- 코드를 입력하세요
SELECT BOARD_ID,	WRITER_ID,	TITLE,	PRICE,	
CASE WHEN STATUS = 'DONE' THEN '거래완료' 
     WHEN STATUS = 'RESERVED' THEN '예약중'
ELSE '판매중' END
FROM USED_GOODS_BOARD
WHERE TO_CHAR(CREATED_DATE, 'YYYYMMDD') = 20221005
ORDER BY BOARD_ID DESC